version: '3'

services:
  database:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: neowayuser
      POSTGRES_PASSWORD: neoway
      POSTGRES_DB: dataclient

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 7000:8080

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python
    networks:
      - neoway-net
    depends_on:
      - database
      - adminer
    ports:
      - "8000:8000"

networks:
  neoway-net:
    driver: bridge